"""add_game_modes_and_stats

Revision ID: 4bad6425d62c
Revises: 1c118866b095
Create Date: 2025-12-25 15:32:41.092712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bad6425d62c'
down_revision: Union[str, None] = '1c118866b095'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_records', sa.Column('game_mode', sa.String(length=20), nullable=False, server_default='beginner'))
    op.add_column('game_records', sa.Column('rows', sa.Integer(), nullable=False, server_default='9'))
    op.add_column('game_records', sa.Column('cols', sa.Integer(), nullable=False, server_default='9'))
    op.add_column('game_records', sa.Column('mines', sa.Integer(), nullable=False, server_default='10'))
    op.drop_constraint(op.f('game_records_id_key'), 'game_records', type_='unique')
    op.drop_constraint(op.f('game_records_user_id_key'), 'game_records', type_='unique')
    op.add_column('users', sa.Column('current_streak', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('best_streak', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('total_games', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'total_games')
    op.drop_column('users', 'best_streak')
    op.drop_column('users', 'current_streak')
    op.create_unique_constraint(op.f('game_records_user_id_key'), 'game_records', ['user_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('game_records_id_key'), 'game_records', ['id'], postgresql_nulls_not_distinct=False)
    op.drop_column('game_records', 'mines')
    op.drop_column('game_records', 'cols')
    op.drop_column('game_records', 'rows')
    op.drop_column('game_records', 'game_mode')
    # ### end Alembic commands ###
